// pages/gallery.vue
<template>
  <div class="page-gallery container">
    <div class="header">
      <h1 class="neon-text">Gallery</h1>
      <p class="text-muted">Moments from our community</p>
    </div>

    <div class="gallery-grid">
      <div v-for="item in gallery" :key="item.id" class="gallery-item glass-panel">
        <PlaceholderImage height="250px" :text="item.title || 'Gallery Image'" />
        <div class="overlay" v-if="item.title">
          <span>{{ item.title }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import PlaceholderImage from '~/components/ui/PlaceholderImage.vue'

useSeoMeta({
  title: 'Gallery - Neraka Portal',
  description: 'View our community gallery.'
})

const { data: gallery } = await useFetch('/api/gallery')
</script>

<style lang="scss" scoped>
.page-gallery {
  padding: var(--spacing-lg) var(--spacing-sm);
}

.header {
  text-align: center;
  margin-bottom: var(--spacing-lg);

  h1 { font-size: 3rem; margin-bottom: 0.5rem; }
}

.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: var(--spacing-sm);
}

.gallery-item {
  position: relative;
  overflow: hidden;
  border-radius: 8px;
  cursor: pointer;

  &:hover .overlay {
    opacity: 1;
  }
}

.overlay {
  position: absolute;
  bottom: 0; left: 0; right: 0;
  background: rgba(0, 0, 0, 0.7);
  padding: 10px;
  text-align: center;
  opacity: 0;
  transition: opacity 0.3s ease;
  span {
    color: white;
    font-family: var(--font-display);
    font-size: 0.9rem;
  }
}
</style>

// src/components/Gallery.jsx
import React from 'react';

const Gallery = () => {
    // Generate some dummy image placeholders
    const images = [
        { id: 1, color: '#FF6B6B' },
        { id: 2, color: '#4ECDC4' },
        { id: 3, color: '#45B7D1' },
        { id: 4, color: '#96CEB4' },
        { id: 5, color: '#FFEEAD' },
        { id: 6, color: '#D4A5A5' },
        { id: 7, color: '#9B59B6' },
        { id: 8, color: '#3498DB' }
    ];

    return (
        <div className="gallery-section" style={{ marginBottom: '60px' }}>
            <h2 className="section-title">Gallery</h2>
            <div className="gallery-grid" style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
                gap: '20px'
            }}>
                {images.map(img => (
                    <div key={img.id} className="gallery-item" style={{
                        height: '200px',
                        backgroundColor: img.color,
                        borderRadius: '12px',
                        position: 'relative',
                        overflow: 'hidden',
                        cursor: 'pointer',
                        transition: 'transform 0.3s ease'
                    }}
                    onMouseOver={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
                    onMouseOut={(e) => e.currentTarget.style.transform = 'scale(1)'}
                    >
                        <div style={{
                            position: 'absolute',
                            bottom: '0',
                            left: '0',
                            width: '100%',
                            padding: '10px',
                            background: 'rgba(0,0,0,0.5)',
                            color: '#fff',
                            fontSize: '14px',
                            textAlign: 'center'
                        }}>
                            Image {img.id}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Gallery;
